version: '3.9'

services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
  
  data-updater:
    build: ./backend/data
    restart: on-failure
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: metalytics
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: