version: '3.9'

services:
  db:
    image: postgres:13
    env_file: 
      - .env  # File containing only DB credentials
    environment:
      POSTGRES_DB: metalytics
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/MetalyticsDump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - metalytics_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - metalytics_net
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: metalytics
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - metalytics_net
    volumes:
      - ./frontend:/app
      - /app/node_modules

  data-updater:
    build:
      context: ./data
      dockerfile: Dockerfile
    env_file: 
      - .env  # File containing only DB credentials
    networks:
      - metalytics_net
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: metalytics
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
  
networks:
  metalytics_net:
    driver: bridge
volumes:
  postgres_data: